package com.namofo.radio.db.greendao3;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.namofo.radio.db.greendao3.generator.Radio;

import com.namofo.radio.db.greendao3.RadioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig radioDaoConfig;

    private final RadioDao radioDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        radioDaoConfig = daoConfigMap.get(RadioDao.class).clone();
        radioDaoConfig.initIdentityScope(type);

        radioDao = new RadioDao(radioDaoConfig, this);

        registerDao(Radio.class, radioDao);
    }
    
    public void clear() {
        radioDaoConfig.clearIdentityScope();
    }

    public RadioDao getRadioDao() {
        return radioDao;
    }

}
